from tkinter import*
from tkinter import messagebox
from PIL import Image,ImageTk
window=Tk()
window.title("My Photo Album")
window.geometry("450x500")
title_label=Label(window,text="My Photo Album",font=("Arial", 20, "bold"), fg="white",bg="purple",width=25)
title_label.pack(pady=15)
image_file1=Image.open("img1.jfif")
image_file1=image_file1.resize((300, 200))
photo1=ImageTk.PhotoImage(image_file1)
pic1=Label(window, image=photo1,bg="purple")
pic1.pack(pady=10)
image_file2=Image.open("img2.jfif")
image_file2=image_file2.resize((300, 200))
photo2=ImageTk.PhotoImage(image_file2)
pic2=Label(window, image=photo2,bg="blue")
pic2.pack(pady=10)
image_file3=Image.open("img3.jfif")
image_file3=image_file3.resize((300, 200))
photo3=ImageTk.PhotoImage(image_file3)
pic3=Label(window, image=photo3, bg="grey")
pic3.pack(pady=10)
image_file4=Image.open("img4.jfif")
image_file4=image_file4.resize((300, 200))
photo4=ImageTk.PhotoImage(image_file4)
pic4=Label(window, image=photo4,bg="pink")
pic4.pack(pady=10)
def show_message():
    messagebox.showinfo("reaction","This is a beautiful images!")
msg_btn=Button(window,text='click to react',bg='blue',fg='white',command=show_message)
msg_btn.pack(pady=5)
def show_details():
    top=Toplevel(window)
    top.title("Photo Details")
    top.geometry("350x250")
    info=Label(top,text="taken on 1 sep 2026",bg="lightyellow",fg="purple")
    info.pack(pady=15)
    top.mainloop()
details_btn=Button(window,text='see the details',bg='lightyellow',fg='brown',command=show_details)
details_btn.pack(pady=10)
window.mainloop()