from tkinter import*
from tkinter import messagebox
from PIL import Image,ImageTk
window=Tk()
window.title("My Photo Album")
window.geometry("450x500")
title_label=Label(window,text="My Photo Album",font=("Arial", 20, "bold"), fg="white",bg="purple",width=25)
title_label.pack(pady=15)
image_file=Image.open("img1.jfif")
image_file=image_file.resize((300, 200))
photo=ImageTk.PhotoImage(image_file)
pic=Label(window, image=photo, bg="lavender")
pic.pack(pady=10)
image_file=Image.open("img2.jfif")
image_file=image_file.resize((300, 200))
photo=ImageTk.PhotoImage(image_file)
pic=Label(window, image=photo, bg="white")
pic.pack(pady=10)
image_file=Image.open("img3.jfif")
image_file=image_file.resize((300, 200))
photo=ImageTk.PhotoImage(image_file)
pic=Label(window, image=photo, bg="grey")
pic.pack(pady=10)
image_file=Image.open("img4.jfif")
image_file=image_file.resize((300, 200))
photo=ImageTk.PhotoImage(image_file)
pic=Label(window, image=photo,bg="pink")
pic.pack(pady=10)
def show_message():
    messagebox.showinfo("This is a beautiful images!")
msg_btn=Button(window,text='click to react',bg='blue',fg='white',command=show_message)
msg_btn.pack(pady=5)
def show_details():
    top=Toplevel(window)
    top.title("Photo Details")
    top.geometry("350x250")
    info=Label(top,text="taken on 1 sep 2026",bg="lightyellow",fg="purple")
    info.pack(pady=15)
    top.mainloop()
details_btn=Button(window,text='see the details',bg='lightyellow',fg='brown',command=show_details)
details_btn.pack(pady=10)
window.mainloop()